// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:circleCheck': typeof import('~icons/akar-icons/circle-check')['default']
    'AkarIcons:eyeOpen': typeof import('~icons/akar-icons/eye-open')['default']
    'AkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    'AkarIcons:triangleAlert': typeof import('~icons/akar-icons/triangle-alert')['default']
    Controls: typeof import('./components/Controls.vue')['default']
    DeleteButton: typeof import('./components/base/DeleteButton.vue')['default']
    ErrorAlert: typeof import('./components/base/ErrorAlert.vue')['default']
    EstimateTable: typeof import('./components/EstimateTable.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Overlay: typeof import('./components/Overlay.vue')['default']
    Tables: typeof import('./components/Tables.vue')['default']
    VoteResult: typeof import('./components/VoteResult.vue')['default']
  }
}

export { }
