// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Controls: typeof import('./components/Controls.vue')['default']
    DeleteButton: typeof import('./components/base/DeleteButton.vue')['default']
    EstimateTable: typeof import('./components/EstimateTable.vue')['default']
    InputModal: typeof import('./components/InputModal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Tables: typeof import('./components/Tables.vue')['default']
    VoteResult: typeof import('./components/VoteResult.vue')['default']
  }
}

export { }
