name: Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2 # setup the repository in the runner
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      # - uses: actions/cache@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm typecheck
      - name: Unit tests
        run: pnpm test:run
      - name: Build
        run: pnpm build
      # deploy site to netlify using secrets created on repository
      # - uses: netlify/actions/cli@master
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     args: deploy --dir=dist --prod
      #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
